# Tutorial

In [1]:
import torch

In [2]:
x = torch.empty(5, 3)

In [3]:
print(x)

tensor([[-1.0158e-09,  4.5828e-41, -1.0158e-09],
        [ 4.5828e-41,  1.8578e-01,  3.9155e-02],
        [ 4.7429e+30,  3.4545e+30,  1.7674e+28],
        [ 1.4586e-19,  8.0318e+20,  1.2737e-14],
        [ 1.3987e-19,  1.3556e-19,  1.8567e-01]])


In [4]:
x = torch.rand(5, 3)

In [5]:
print(x)

tensor([[0.7484, 0.9138, 0.6527],
        [0.5666, 0.7122, 0.8031],
        [0.5297, 0.1329, 0.0733],
        [0.3726, 0.5620, 0.2188],
        [0.2699, 0.4164, 0.6241]])


In [6]:
x = torch.tensor([5.5, 3])

In [7]:
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)

In [9]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.rand_like(x, dtype=torch.float)

In [11]:
print(x)

tensor([[0.4088, 0.8298, 0.2841],
        [0.7177, 0.8947, 0.6523],
        [0.1147, 0.4136, 0.2465],
        [0.8563, 0.1196, 0.9705],
        [0.0590, 0.8761, 0.3310]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
y = torch.rand(5, 3)

In [14]:
print(y)

tensor([[0.5964, 0.8406, 0.6054],
        [0.3570, 0.3539, 0.0353],
        [0.8046, 0.2560, 0.7439],
        [0.2968, 0.7732, 0.9963],
        [0.3284, 0.6227, 0.7085]])


In [15]:
print(x + y)

tensor([[1.0051, 1.6704, 0.8896],
        [1.0746, 1.2486, 0.6877],
        [0.9193, 0.6696, 0.9905],
        [1.1530, 0.8928, 1.9668],
        [0.3875, 1.4988, 1.0395]])


In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[ 0.8454,  0.1359,  1.1318, -0.8598],
        [ 1.3526, -2.2602, -0.8047,  1.1497],
        [ 0.3975,  2.9792, -0.0393, -1.2598],
        [ 0.2595,  1.2963,  1.5414, -0.1258]], device='cuda:0')
tensor([[ 0.8454,  0.1359,  1.1318, -0.8598],
        [ 1.3526, -2.2602, -0.8047,  1.1497],
        [ 0.3975,  2.9792, -0.0393, -1.2598],
        [ 0.2595,  1.2963,  1.5414, -0.1258]], dtype=torch.float64)


## AutoGrad

In [20]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [21]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [22]:
print(y.grad_fn)

In [23]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [24]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [25]:
a.requires_grad_(True)

tensor([[ 0.9018, -2.6237],
        [-4.5635,  1.3455]], requires_grad=True)

In [26]:
print(a.requires_grad)

True


In [27]:
b = (a * a).sum()
print(b.requires_grad)

True


In [28]:
print(b.grad_fn)

In [29]:
a.requires_grad_(False)

tensor([[ 0.9018, -2.6237],
        [-4.5635,  1.3455]])

In [30]:
b = (a + 2) / 5

In [31]:
print(b.requires_grad)

False


In [36]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()

In [37]:
out.backward()

In [38]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [39]:
x = torch.randn(3, requires_grad=True)

In [40]:
print(x)

tensor([0.6198, 0.0545, 0.2636], requires_grad=True)


In [41]:
y = x * 2

In [42]:
print(y)

tensor([1.2397, 0.1090, 0.5272], grad_fn=<MulBackward0>)


In [43]:
print(y.data)

tensor([1.2397, 0.1090, 0.5272])


In [53]:
while y.norm() < 1000:
    y = y*2

In [54]:
print(y)

tensor([1269.4146,  111.5892,  539.8127], grad_fn=<MulBackward0>)


In [56]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float)

In [57]:
y.backward(v)

In [58]:
print(x.grad)

tensor([ 204.8000, 2048.0000,    2.0480])


In [59]:
print(x.requires_grad)
print((x*2).requires_grad)

with torch.no_grad():
    print((x*2).requires_grad)

True
True
False
